services:
  postgres:
    image: postgres:17.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 9876:5432
    volumes:
      - nofer-api-postgres:/var/lib/postgresql/data

volumes:
  nofer-api-postgres: